### ISSUE TITLE
"Not valid OpenAI API Access Key" Error

### ISSUE THREAD

**Issue by marcantoniolafranca** [RobertoCorti/gptravel#28]
Hi, I'm trying to test the app on streamlit, but I get always:
"Not valid OpenAI API Access Key"

I tried with both types of OpenAI keys (user and project).
Am I doing something wrong?
![image](https://github.com/RobertoCorti/gptravel/assets/155981498/171b1692-483a-4064-a274-461a310356fc)

**Comment by RobertoCorti** [comment]
Hey

Thanks for reaching out. No, the issue was due to an error triggered by OpenAI as we were utilizing a deprecated model. We have just updated the call. 

Let us know if it is working now and if you wanna contribute to the project. @stefano-polo and I are pretty busy with our jobs and a help would be greatly appreciated 😄 

Cheers!
